import pg from "pg";
const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const conditions = [
  {
    name: "Acne Vulgaris",
    slug: "acne-vulgaris",
    category: "acne",
    severity: "moderate",
    description: "The most common form of acne, characterised by blocked hair follicles leading to pimples, blackheads and whiteheads on the face, chest and back.",
    symptoms: ["Blackheads", "Whiteheads", "Papules", "Pustules", "Oily skin", "Scarring"],
    triggers: ["Excess sebum", "Bacteria (C. acnes)", "Hormonal changes", "Diet", "Stress"],
    recommendedIngredients: ["Salicylic acid", "Benzoyl peroxide", "Niacinamide", "Zinc", "Tea tree oil", "Retinoids", "Azelaic acid"],
    avoidIngredients: ["Coconut oil", "Heavy mineral oils", "Alcohol denat", "Fragrance"],
    productCategories: ["Facial Cleansers & Scrubs", "Facial Toners", "Facial Serums & Treatments", "Facial Masks & Peels"],
    aiKeywords: ["acne", "pimple", "breakout", "comedone", "blackhead", "whitehead", "blemish", "clogged pore"],
    treatmentSteps: ["Cleanse twice daily with salicylic acid", "Apply niacinamide serum morning and evening", "Use benzoyl peroxide spot treatment at night", "Always apply non-comedogenic SPF 30+ in the morning"],
  },
  {
    name: "Cystic Acne",
    slug: "cystic-acne",
    category: "acne",
    severity: "severe",
    description: "A severe form of acne where blocked pores become deeply infected, forming large painful cysts beneath the skin surface that can cause permanent scarring.",
    symptoms: ["Large painful cysts", "Deep inflammation", "Scarring", "Nodules", "Severe redness"],
    triggers: ["Hormonal imbalances", "Genetics", "High androgen levels", "Dairy consumption"],
    recommendedIngredients: ["Benzoyl peroxide 2.5–5%", "Retinoids", "Azelaic acid", "Niacinamide", "Centella asiatica"],
    avoidIngredients: ["Comedogenic oils", "Physical exfoliants", "Alcohol", "Fragrance"],
    productCategories: ["Facial Cleansers & Scrubs", "Facial Serums & Treatments", "Facial Masks & Peels"],
    aiKeywords: ["cystic acne", "deep pimple", "cyst", "nodule", "severe breakout", "inflamed"],
    treatmentSteps: ["Use gentle non-stripping cleanser", "Apply prescribed topical retinoid at night", "Ice inflamed areas to reduce swelling", "Never pick or squeeze cysts", "Consult a dermatologist"],
  },
  {
    name: "Post-Inflammatory Hyperpigmentation (PIH)",
    slug: "post-inflammatory-hyperpigmentation",
    category: "pigmentation",
    severity: "moderate",
    description: "Dark marks left behind after acne, cuts or inflammation heal. The skin overproduces melanin during healing, leaving flat discolouration on the skin.",
    symptoms: ["Dark flat spots", "Uneven skin tone", "Brown/red/purple marks", "Discolouration after breakouts"],
    triggers: ["Picking at skin", "Inflammation", "UV exposure", "Hormonal changes"],
    recommendedIngredients: ["Vitamin C", "Niacinamide", "Alpha Arbutin", "Tranexamic acid", "Kojic acid", "AHA (glycolic, lactic)", "Retinoids"],
    avoidIngredients: ["Irritants that increase inflammation", "Alcohol"],
    productCategories: ["Facial Serums & Treatments", "Facial Toners", "Facial Moisturisers & Oils"],
    aiKeywords: ["dark spots", "hyperpigmentation", "acne marks", "post-acne", "discolouration", "uneven tone", "dark marks"],
    treatmentSteps: ["Apply Vitamin C serum every morning", "Use niacinamide or alpha arbutin serum", "Exfoliate with AHA 2–3 times a week", "ALWAYS wear SPF 50+ — UV makes PIH worse", "Be patient: fading takes 3–6 months"],
  },
  {
    name: "Melasma",
    slug: "melasma",
    category: "pigmentation",
    severity: "moderate",
    description: "A chronic pigmentation condition causing symmetrical brown or grey-brown patches, most commonly on the cheeks, forehead and upper lip. Strongly linked to sun exposure and hormones.",
    symptoms: ["Symmetrical brown patches", "Darker patches on cheeks/forehead/lip", "Worsens with sun exposure"],
    triggers: ["Sun exposure", "Hormonal changes (pregnancy, pill)", "Heat", "Genetics"],
    recommendedIngredients: ["Tranexamic acid", "Kojic acid", "Alpha arbutin", "Niacinamide", "Azelaic acid", "Vitamin C"],
    avoidIngredients: ["Retinoids (can irritate)", "Strong acids without SPF", "Heat exposure"],
    productCategories: ["Facial Serums & Treatments", "Sun Protection", "Facial Moisturisers & Oils"],
    aiKeywords: ["melasma", "chloasma", "pregnancy mask", "brown patches", "symmetrical pigmentation"],
    treatmentSteps: ["SPF 50+ every day — non-negotiable", "Apply tranexamic acid or kojic acid serum", "Avoid heat triggers", "Use tinted SPF for extra UVA protection", "See a dermatologist for prescription hydroquinone if needed"],
  },
  {
    name: "Periorbital Dark Circles",
    slug: "dark-circles",
    category: "eye-concerns",
    severity: "mild",
    description: "Darkening of the under-eye area caused by a combination of thin skin, visible blood vessels, pigmentation, fat loss and dehydration.",
    symptoms: ["Dark under-eye colouration", "Puffiness", "Hollow appearance", "Blue or brown tint"],
    triggers: ["Sleep deprivation", "Dehydration", "Genetics", "Allergies", "Ageing", "Iron deficiency"],
    recommendedIngredients: ["Caffeine", "Vitamin C", "Retinol", "Peptides", "Hyaluronic acid", "Vitamin K"],
    avoidIngredients: ["Fragrance in eye area", "Harsh rubbing"],
    productCategories: ["Eye Skincare Treatments", "Facial Serums & Treatments"],
    aiKeywords: ["dark circles", "under eye", "periorbital", "eye bags", "puffiness", "dark under eyes"],
    treatmentSteps: ["Apply caffeine eye gel in the morning to depuff", "Use vitamin C serum under eye for brightening", "Keep head elevated while sleeping", "Cold compresses to reduce puffiness", "Stay well hydrated"],
  },
  {
    name: "Periorbital Puffiness",
    slug: "eye-puffiness",
    category: "eye-concerns",
    severity: "mild",
    description: "Swelling or puffiness around the eyes caused by fluid retention, lack of sleep, or lymphatic drainage issues.",
    symptoms: ["Swollen under-eyes", "Morning puffiness", "Fluid retention", "Heavy-looking eyes"],
    triggers: ["Salt-heavy diet", "Alcohol", "Lack of sleep", "Allergies", "Crying"],
    recommendedIngredients: ["Caffeine", "Green tea extract", "Peptides", "Cucumber extract", "Niacinamide"],
    avoidIngredients: ["Heavy creams that block drainage", "Salty food before bed"],
    productCategories: ["Eye Skincare Treatments"],
    aiKeywords: ["puffy eyes", "eye puffiness", "swollen eyes", "baggy eyes"],
    treatmentSteps: ["Apply chilled caffeine eye gel each morning", "Sleep with head slightly elevated", "Reduce salt and alcohol intake", "Gentle lymphatic drainage massage around eyes"],
  },
  {
    name: "Dehydrated Skin",
    slug: "dehydrated-skin",
    category: "hydration",
    severity: "mild",
    description: "A skin condition (not a skin type) where the skin lacks water. Affects all skin types including oily skin and is often temporary and treatable.",
    symptoms: ["Tight feeling after cleansing", "Dull complexion", "Fine dehydration lines", "Flakiness over oily areas", "Emphasised wrinkles"],
    triggers: ["Insufficient water intake", "Harsh cleansers", "Weather changes", "Air conditioning", "Over-exfoliation"],
    recommendedIngredients: ["Hyaluronic acid", "Glycerin", "Beta-glucan", "Panthenol (B5)", "Ceramides", "Aloe vera"],
    avoidIngredients: ["Alcohol denat", "Stripping cleansers", "Over-exfoliation"],
    productCategories: ["Facial Moisturisers & Oils", "Facial Serums & Treatments", "Facial Masks & Peels"],
    aiKeywords: ["dehydrated", "dry feeling", "tight skin", "dull skin", "lacks moisture", "hydration"],
    treatmentSteps: ["Apply hyaluronic acid serum to damp skin", "Layer a ceramide moisturiser on top immediately", "Use a gentle non-stripping cleanser", "Drink 2+ litres of water daily", "Use a hydrating sheet mask 2–3 times weekly"],
  },
  {
    name: "Xerosis (Dry Skin)",
    slug: "dry-skin",
    category: "hydration",
    severity: "mild",
    description: "Chronic dry skin caused by reduced sebum production and impaired skin barrier function, resulting in rough, flaky and sometimes cracked skin.",
    symptoms: ["Flakiness", "Rough texture", "Cracking", "Itching", "Redness", "Tight feeling"],
    triggers: ["Low humidity", "Hot showers", "Harsh soaps", "Ageing", "Genetics", "Certain medications"],
    recommendedIngredients: ["Ceramides", "Shea butter", "Squalane", "Hyaluronic acid", "Glycerin", "Fatty acids", "Cholesterol"],
    avoidIngredients: ["Alcohol denat", "Fragrances", "Sulphates", "Hot water"],
    productCategories: ["Facial Moisturisers & Oils", "Facial Serums & Treatments"],
    aiKeywords: ["dry skin", "flaky", "rough skin", "xerosis", "cracked skin", "scaling"],
    treatmentSteps: ["Cleanse with oil or cream cleanser only", "Apply rich ceramide moisturiser within 60 seconds of washing", "Use squalane oil as final step to lock in moisture", "Avoid hot showers — use lukewarm water", "Run a humidifier in dry environments"],
  },
  {
    name: "Oily Skin / Hyperseborrhoea",
    slug: "oily-skin",
    category: "oiliness",
    severity: "mild",
    description: "Overproduction of sebum (skin oil) by the sebaceous glands, resulting in a shiny appearance, enlarged pores and increased susceptibility to acne.",
    symptoms: ["Shiny skin by midday", "Enlarged pores", "Acne-prone", "Makeup doesn't last", "Thick skin texture"],
    triggers: ["Genetics", "Hormones", "Humidity", "Over-washing (strips skin, triggers more oil)"],
    recommendedIngredients: ["Niacinamide", "Salicylic acid", "Zinc", "Clay (kaolin, bentonite)", "Retinoids", "AHA"],
    avoidIngredients: ["Heavy occlusive oils", "Coconut oil", "Rich butters"],
    productCategories: ["Facial Cleansers & Scrubs", "Facial Toners", "Facial Masks & Peels"],
    aiKeywords: ["oily skin", "excess oil", "sebum", "shiny skin", "greasy", "oil control"],
    treatmentSteps: ["Use a gel or foaming salicylic acid cleanser twice daily", "Apply niacinamide serum to balance sebum", "Use a clay mask 1–2 times a week", "Choose oil-free, non-comedogenic moisturiser", "Use blotting papers throughout the day"],
  },
  {
    name: "Rosacea",
    slug: "rosacea",
    category: "sensitivity",
    severity: "moderate",
    description: "A chronic inflammatory skin condition causing facial redness, visible blood vessels, and sometimes pus-filled bumps. Most common in fair-skinned individuals.",
    symptoms: ["Facial redness", "Visible blood vessels", "Burning/stinging sensation", "Skin thickening", "Eye irritation"],
    triggers: ["Sun exposure", "Alcohol", "Spicy food", "Heat", "Exercise", "Stress", "Wind"],
    recommendedIngredients: ["Azelaic acid", "Niacinamide", "Centella asiatica", "Green tea extract", "Aloe vera", "Gentle ceramides"],
    avoidIngredients: ["Alcohol", "Fragrance", "Menthol", "Physical exfoliants", "Retinoids (initially)", "AHA/BHA at high percentages"],
    productCategories: ["Facial Moisturisers & Oils", "Facial Serums & Treatments", "Sun Protection"],
    aiKeywords: ["rosacea", "redness", "flushing", "red cheeks", "visible veins", "facial redness", "couperose"],
    treatmentSteps: ["Use fragrance-free gentle cleanser", "Apply azelaic acid serum", "Use mineral SPF only", "Identify and avoid personal triggers", "Consult a dermatologist for prescription topicals"],
  },
  {
    name: "Eczema / Atopic Dermatitis",
    slug: "eczema",
    category: "sensitivity",
    severity: "moderate",
    description: "A chronic inflammatory skin condition causing intensely itchy, dry, and inflamed patches. Related to a weakened skin barrier and often associated with allergies and asthma.",
    symptoms: ["Intense itching", "Dry patches", "Inflamed red skin", "Weeping/crusting", "Thickened skin", "Cracking"],
    triggers: ["Irritants (soaps, detergents)", "Allergens", "Stress", "Weather", "Sweat", "Certain fabrics"],
    recommendedIngredients: ["Ceramides", "Colloidal oatmeal", "Glycerin", "Shea butter", "Panthenol", "Squalane"],
    avoidIngredients: ["Fragrance", "Dyes", "Sulphates", "Alcohol denat", "Lanolin (sometimes)", "Preservatives"],
    productCategories: ["Facial Moisturisers & Oils", "Therapeutic Skincare"],
    aiKeywords: ["eczema", "atopic dermatitis", "itchy skin", "inflamed patches", "dry itchy"],
    treatmentSteps: ["Moisturise immediately after bathing with ceramide cream", "Use fragrance-free products only", "Identify and eliminate triggers", "Apply prescription steroid cream during flares as directed", "Keep skin cool — heat worsens eczema"],
  },
  {
    name: "Fine Lines & Wrinkles",
    slug: "wrinkles",
    category: "ageing",
    severity: "mild",
    description: "Natural signs of skin ageing caused by the breakdown of collagen and elastin fibres, repeated facial expressions, UV damage and loss of facial volume.",
    symptoms: ["Fine surface lines", "Deeper wrinkles", "Skin laxity", "Thinning skin", "Loss of plumpness"],
    triggers: ["Sun exposure (photoageing)", "Smoking", "Repetitive expressions", "Natural ageing", "Dehydration"],
    recommendedIngredients: ["Retinol/Retinoids", "Peptides", "Vitamin C", "Hyaluronic acid", "Niacinamide", "AHA", "Coenzyme Q10"],
    avoidIngredients: ["Alcohol denat", "Fragrance", "Harsh scrubs"],
    productCategories: ["Facial Serums & Treatments", "Facial Moisturisers & Oils", "Eye Skincare Treatments", "Sun Protection"],
    aiKeywords: ["wrinkles", "fine lines", "anti-aging", "ageing", "crow's feet", "forehead lines", "expression lines"],
    treatmentSteps: ["Apply retinol 2–3 nights a week, building up frequency", "Use peptide serum morning and evening", "Vitamin C serum each morning for antioxidant protection", "SPF 50+ every single day", "Hyaluronic acid serum for plumping"],
  },
  {
    name: "Sun Damage / Photoageing",
    slug: "sun-damage",
    category: "pigmentation",
    severity: "moderate",
    description: "Cumulative skin damage from UV radiation causing premature ageing, irregular pigmentation, broken capillaries, and increased skin cancer risk.",
    symptoms: ["Brown sunspots", "Leathery texture", "Broken capillaries", "Uneven tone", "Deep wrinkles", "Loss of elasticity"],
    triggers: ["Cumulative UV exposure", "Not wearing SPF", "Tanning beds"],
    recommendedIngredients: ["Vitamin C", "Niacinamide", "Retinoids", "AHA", "Antioxidants", "Resveratrol"],
    avoidIngredients: ["Anything that increases photosensitivity without SPF"],
    productCategories: ["Sun Protection", "Facial Serums & Treatments", "Facial Moisturisers & Oils"],
    aiKeywords: ["sun damage", "sunspot", "age spot", "solar lentigo", "photoaging", "UV damage", "brown spots"],
    treatmentSteps: ["Apply SPF 50+ every morning — this is the most important step", "Use Vitamin C serum to target existing spots", "Introduce retinoid at night for cellular renewal", "AHA exfoliation 2× per week to fade surface discolouration"],
  },
  {
    name: "Enlarged Pores",
    slug: "enlarged-pores",
    category: "texture",
    severity: "mild",
    description: "Visibly stretched pore openings most common in the T-zone, caused by excess sebum, reduced skin elasticity, and sun damage.",
    symptoms: ["Visible pores on nose/cheeks", "Rough skin texture", "Blackheads in pores", "Oily skin"],
    triggers: ["Excess sebum", "Loss of skin elasticity", "UV damage", "Genetics"],
    recommendedIngredients: ["Niacinamide", "Salicylic acid", "Retinoids", "AHA", "Clay minerals"],
    avoidIngredients: ["Heavy pore-clogging products"],
    productCategories: ["Facial Toners", "Facial Serums & Treatments", "Facial Masks & Peels"],
    aiKeywords: ["enlarged pores", "large pores", "open pores", "visible pores", "pore size"],
    treatmentSteps: ["Use salicylic acid toner to keep pores clear", "Apply niacinamide serum to minimise appearance", "Clay mask weekly to draw out impurities", "Retinol at night to improve skin elasticity and tighten pores"],
  },
  {
    name: "Uneven Skin Tone",
    slug: "uneven-skin-tone",
    category: "pigmentation",
    severity: "mild",
    description: "Patchy or irregular skin tone caused by an uneven distribution of melanin across the face. Includes redness, dullness, and light/dark patches.",
    symptoms: ["Patchy complexion", "Dull skin", "Redness", "Mixed light and dark areas"],
    triggers: ["Sun exposure", "Inflammation", "Hormones", "Dehydration"],
    recommendedIngredients: ["Niacinamide", "Vitamin C", "AHA", "Alpha arbutin"],
    avoidIngredients: ["Harsh abrasives"],
    productCategories: ["Facial Serums & Treatments", "Facial Toners", "Facial Moisturisers & Oils"],
    aiKeywords: ["uneven skin tone", "patchy skin", "dull complexion", "discolouration", "blotchy"],
    treatmentSteps: ["Exfoliate 2× weekly with AHA", "Apply niacinamide serum daily", "Vitamin C serum in the morning for brightening", "Use SPF to prevent further unevenness"],
  },
  {
    name: "Sensitive Skin",
    slug: "sensitive-skin",
    category: "sensitivity",
    severity: "mild",
    description: "A tendency to experience stinging, burning, redness or itching in response to products or environmental factors, due to a compromised or reactive skin barrier.",
    symptoms: ["Stinging/burning after product use", "Redness", "Itching", "Flushing", "Breakouts from new products"],
    triggers: ["Fragrance", "Alcohol", "Acids", "Environmental changes", "Stress"],
    recommendedIngredients: ["Ceramides", "Centella asiatica", "Aloe vera", "Oat extract", "Glycerin", "Panthenol"],
    avoidIngredients: ["Fragrance", "Alcohol denat", "Essential oils", "Harsh actives", "Menthol", "Sulphates"],
    productCategories: ["Facial Moisturisers & Oils", "Therapeutic Skincare", "Facial Cleansers & Scrubs"],
    aiKeywords: ["sensitive skin", "reactivity", "stinging", "burning skin", "reactive skin"],
    treatmentSteps: ["Patch test every new product", "Use only fragrance-free, hypoallergenic products", "Simplify routine to 3–4 products max", "Strengthen skin barrier with ceramide moisturiser", "Introduce actives one at a time, slowly"],
  },
  {
    name: "Seborrheic Dermatitis",
    slug: "seborrheic-dermatitis",
    category: "sensitivity",
    severity: "moderate",
    description: "A common skin condition causing scaly patches, red skin and stubborn dandruff on oily areas like the scalp, face and inside the ear. Linked to yeast overgrowth.",
    symptoms: ["Flaky white/yellow scales", "Red skin", "Greasy patches", "Itching", "Dandruff"],
    triggers: ["Stress", "Cold weather", "Oily skin", "Yeast overgrowth", "Hormonal changes"],
    recommendedIngredients: ["Zinc pyrithione", "Ketoconazole", "Salicylic acid", "Selenium sulphide", "Tea tree oil"],
    avoidIngredients: ["Heavy occlusive products", "Products that promote yeast growth"],
    productCategories: ["Therapeutic Skincare", "Facial Cleansers & Scrubs", "Facial Toners"],
    aiKeywords: ["seborrheic dermatitis", "dandruff", "flaking", "oily flakes", "scalp issues"],
    treatmentSteps: ["Use antifungal face wash containing zinc or ketoconazole", "Keep affected areas clean and dry", "Avoid heavy creams on affected areas", "Manage stress as it worsens flares"],
  },
  {
    name: "Psoriasis",
    slug: "psoriasis",
    category: "sensitivity",
    severity: "severe",
    description: "An autoimmune condition causing rapid skin cell turnover, resulting in thick, silvery-scaled plaques that are often itchy and painful.",
    symptoms: ["Thick silvery plaques", "Inflamed red patches", "Itching and burning", "Dry cracked skin", "Joint pain (psoriatic arthritis)"],
    triggers: ["Stress", "Infections", "Skin injuries", "Certain medications", "Alcohol"],
    recommendedIngredients: ["Coal tar", "Salicylic acid", "Ceramides", "Aloe vera", "Oat extract"],
    avoidIngredients: ["Anything that triggers inflammation", "Fragrance", "Alcohol"],
    productCategories: ["Therapeutic Skincare", "Facial Moisturisers & Oils"],
    aiKeywords: ["psoriasis", "silvery scales", "plaques", "autoimmune skin", "scaly patches"],
    treatmentSteps: ["Moisturise affected areas daily with thick ceramide cream", "Use prescribed topical treatments as directed", "Avoid known triggers", "Consider phototherapy under medical supervision", "See a dermatologist for systemic treatment if severe"],
  },
  {
    name: "Combination Skin",
    slug: "combination-skin",
    category: "skin-type",
    severity: "mild",
    description: "Skin that displays characteristics of both oily and dry skin — typically an oily T-zone (forehead, nose, chin) and dry/normal cheeks.",
    symptoms: ["Shiny T-zone", "Dry or normal cheeks", "Enlarged pores in T-zone", "Occasional breakouts"],
    triggers: ["Genetics", "Hormonal fluctuations", "Seasonal changes"],
    recommendedIngredients: ["Niacinamide", "Hyaluronic acid", "Lightweight moisturisers", "AHA/BHA balance"],
    avoidIngredients: ["Very heavy creams over T-zone", "Very stripping cleansers"],
    productCategories: ["Facial Moisturisers & Oils", "Facial Toners", "Facial Cleansers & Scrubs"],
    aiKeywords: ["combination skin", "oily t-zone", "mixed skin", "t-zone oily"],
    treatmentSteps: ["Multi-masking: clay on T-zone, hydrating mask on cheeks", "Use balanced gel-cream moisturiser", "Apply niacinamide to regulate sebum", "Lightweight toner to balance pH"],
  },
  {
    name: "Ingrown Hairs / Folliculitis",
    slug: "folliculitis",
    category: "acne",
    severity: "mild",
    description: "Inflammation of hair follicles caused by bacterial or fungal infection, resulting in pimple-like bumps. Often confused with acne.",
    symptoms: ["Small red bumps", "Itching", "Tenderness", "Pus-filled bumps", "Ingrown hairs"],
    triggers: ["Shaving", "Tight clothing", "Sweat", "Waxing", "Hair removal"],
    recommendedIngredients: ["Salicylic acid", "Benzoyl peroxide", "Tea tree oil", "Glycolic acid"],
    avoidIngredients: ["Heavy oils that clog follicles"],
    productCategories: ["Facial Cleansers & Scrubs", "Facial Serums & Treatments"],
    aiKeywords: ["folliculitis", "ingrown hair", "bumpy skin", "hair follicle"],
    treatmentSteps: ["Exfoliate gently with salicylic acid 2–3 times a week", "Keep area clean and dry", "Avoid shaving over active bumps", "Use lightweight non-comedogenic moisturiser"],
  },
];

async function main() {
  console.log("Seeding skin conditions...");

  await pool.query("DELETE FROM skin_conditions");

  for (const cond of conditions) {
    await pool.query(
      `INSERT INTO skin_conditions 
        (name, slug, category, severity, description, symptoms, triggers, 
         recommended_ingredients, avoid_ingredients, product_categories, ai_keywords, treatment_steps)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,
      [
        cond.name,
        cond.slug,
        cond.category,
        cond.severity,
        cond.description,
        cond.symptoms,
        cond.triggers,
        cond.recommendedIngredients,
        cond.avoidIngredients,
        cond.productCategories,
        cond.aiKeywords,
        cond.treatmentSteps,
      ]
    );
  }

  const { rows } = await pool.query("SELECT category, COUNT(*) as count FROM skin_conditions GROUP BY category ORDER BY count DESC");
  console.log(`\n✅ Seeded ${conditions.length} skin conditions:`);
  rows.forEach((r: any) => console.log(`  ${r.category}: ${r.count}`));

  await pool.end();
}

main().catch((e) => {
  console.error("Error:", e.message);
  process.exit(1);
});
