[[pages]]
path = "/"
screenshotTimestamp = "2026-03-20T07:11:00Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/0a3680a2-1a2c-4d6d-ae54-2094bdb634cf/417c78a6-3666-4f30-a3e8-20d280e8a83e/tjB0Id7"

[[pages]]
path = "/products"
screenshotTimestamp = "2026-03-19T06:50:21Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/0a3680a2-1a2c-4d6d-ae54-2094bdb634cf/417c78a6-3666-4f30-a3e8-20d280e8a83e/J2OhytK"

[[pages]]
path = "/login"
screenshotTimestamp = "2026-03-20T07:11:02Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/0a3680a2-1a2c-4d6d-ae54-2094bdb634cf/417c78a6-3666-4f30-a3e8-20d280e8a83e/UBkg4BC"
